// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQKYm4lwE3oN-abxXVXN9-hmxe7-HRd4M',
    appId: '1:245225796242:web:8e08e06c312e9aee336c4b',
    messagingSenderId: '245225796242',
    projectId: 'recipe-lab3',
    authDomain: 'recipe-lab3.firebaseapp.com',
    storageBucket: 'recipe-lab3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPq8jLjuqEOaJ9Xtw-ws6IPNlg8ZU1_vk',
    appId: '1:245225796242:android:736fae40bb930939336c4b',
    messagingSenderId: '245225796242',
    projectId: 'recipe-lab3',
    storageBucket: 'recipe-lab3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-4Lqt_2jjZ2emTtMIKIjMx3XFirZZo2E',
    appId: '1:245225796242:ios:872bd6135496335b336c4b',
    messagingSenderId: '245225796242',
    projectId: 'recipe-lab3',
    storageBucket: 'recipe-lab3.firebasestorage.app',
    iosBundleId: 'com.example.recipe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-4Lqt_2jjZ2emTtMIKIjMx3XFirZZo2E',
    appId: '1:245225796242:ios:872bd6135496335b336c4b',
    messagingSenderId: '245225796242',
    projectId: 'recipe-lab3',
    storageBucket: 'recipe-lab3.firebasestorage.app',
    iosBundleId: 'com.example.recipe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQKYm4lwE3oN-abxXVXN9-hmxe7-HRd4M',
    appId: '1:245225796242:web:d69fef3e0e650ffa336c4b',
    messagingSenderId: '245225796242',
    projectId: 'recipe-lab3',
    authDomain: 'recipe-lab3.firebaseapp.com',
    storageBucket: 'recipe-lab3.firebasestorage.app',
  );
}
